In [1]:
import numpy as np

### Crear un vector con valores dentro del rango 10 a 49

In [54]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Invertir el vector

In [55]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

### Crear una matriz 3x3 con valores de 0 a 8

In [56]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Encontrar los indices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0]

In [57]:
a = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
np.argwhere( a!=0 )

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 6],
       [10],
       [11],
       [12],
       [13],
       [14]])

### Crear una matriz identidad de 6x6

In [58]:
np.identity(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

### Crear una matriz con valores al azar con forma 3x3x3 

In [59]:
r = np.random.random((3,3,3))
r

array([[[ 0.76397724,  0.44106772,  0.61463619],
        [ 0.78438605,  0.27900196,  0.37379515],
        [ 0.13011713,  0.25126419,  0.08604375]],

       [[ 0.9668768 ,  0.90837987,  0.958807  ],
        [ 0.72465688,  0.2603027 ,  0.05378951],
        [ 0.84580746,  0.64123084,  0.17195369]],

       [[ 0.56064236,  0.13471053,  0.60909779],
        [ 0.95955252,  0.06483762,  0.16022758],
        [ 0.72095279,  0.74251344,  0.11964072]]])

### Encontrar los indices de los valores minimos y maximos de la anterior matriz

In [62]:
print( r.argmax() )
print( r.ravel()[r.argmax()] )

print(r)
print(np.unravel_index(r.argmax(), r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

9
0.966876800689
[[[ 0.76397724  0.44106772  0.61463619]
  [ 0.78438605  0.27900196  0.37379515]
  [ 0.13011713  0.25126419  0.08604375]]

 [[ 0.9668768   0.90837987  0.958807  ]
  [ 0.72465688  0.2603027   0.05378951]
  [ 0.84580746  0.64123084  0.17195369]]

 [[ 0.56064236  0.13471053  0.60909779]
  [ 0.95955252  0.06483762  0.16022758]
  [ 0.72095279  0.74251344  0.11964072]]]
(1, 0, 0)


0.96687680068865456

### Crear una matriz de 10x10 con 1's en los bordes y 0 en el interior (con rangos de indices)

In [45]:
z = np.ones((10,10))

z[1:-1,1:-1] = 0
z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

### Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [63]:
np.tile( np.arange(0,5) , 5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Crear dos arreglos al azar A y B, verificar si son iguales

In [64]:
a = np.random.random((3,3))
b = np.random.random((3,3))

a == b 

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [65]:
np.allclose(a,b)  # Con tolerancia, dada por argumentos: rtol atol


False

In [66]:
np.array_equal(a,b)

False