## Numpy Basics - Resume
### Diferencias con la sintaxis de matlab
----

In [3]:
# La convencion para el uso de NumPy
import numpy as np 

In [4]:
# Creando un arreglo, a partir de una lista de python
lista_python = [0,1,2,3] 
mi_array = np.array( [0,1,2,3,5] )
print (mi_array)

[0 1 2 3 5]


```matlab
% En matlab
mi_array = [0 1 2 3] ;
```

In [5]:
mi_array = np.arange(0,10)
mi_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Usando metodos de creacion de arreglos multidimensionales
# ones, zeros, identity, eye
mi_array = np.ones( (3,3) )
mi_array

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

El resto de los metodos para crear arreglos que ofrece numpy:<br>
http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html<br>

----

In [7]:
# Que hay dentro del objeto mi_arreglo
print ('Numero de elementos ' , mi_array.size)
print ('Forma dimensiones ' , mi_array.shape)
print ('Numero dimensiones ' , mi_array.ndim)
print ('Tipo de dato ' , mi_array.dtype)

#dir(mi_array)

Numero de elementos  9
Forma dimensiones  (3, 3)
Numero dimensiones  2
Tipo de dato  float64


```matlab
% En matlab
numel(mi_array) 
size(mi_array)
```

### Visualizando la informacion
- Ultimo eje se visualiza de izquieda a derecha
- Penultimo eje se visualiza de arriba a abajo.
- El resto tambien se muestran de arriba a abajo, donde cada bloque es separado del siguiente por una linea vacia.

In [8]:
# arreglo 2D
a = np.arange(12)
a.resize(4,3)
print (a[:])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [9]:
# arrreglo 3D
c = np.arange(24).reshape(2,3,4)
print (c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Las operaciones basicas
Todas las operaciones aritmeticas sobre los arreglos de numpy se hacen elemento a elemento. Se genera un nuevo arreglo y se llena con el resultado

In [10]:
a = np.arange(4).reshape(2,2)
b = np.ones((2,2))
b = b + 1
c = a * b 
print (a) 
print (b) 
print ('-')
print (c)

[[0 1]
 [2 3]]
[[ 2.  2.]
 [ 2.  2.]]
-
[[ 0.  2.]
 [ 4.  6.]]


```matlab
% En matlab
>> c = a .* b
```

In [11]:
# El producto de matrices
c = np.dot(a,b)
print (c)

[[  2.   2.]
 [ 10.  10.]]


```matlab
% En matlab 
>>> c = a * b
```

#### "Broadcasting"
Describe el como se comportan los arreglos de numpy de diferenctes dimensiones durante las operaciones aritmeticas.

In [12]:
# "Broadcasting" Operaciones sobre arreglos que no tienen la misma dimension, se repiten en los siguientes bloques
# Regla del broadcasting dice que dos dimensiones son compatibles cuando: 
# - Son iguales en las primeras dimensiones
# - Una de ellas es uno.

a = np.arange(12).reshape(4,3)
b = np.ones((3))

print (a, '-', b)
print ('=')
print (a - b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] - [ 1.  1.  1.]
=
[[ -1.   0.   1.]
 [  2.   3.   4.]
 [  5.   6.   7.]
 [  8.   9.  10.]]


In [17]:
# Otro ejemplo de "broadcasting"
x = np.arange(4)
xx = x.reshape(4,1)
print ('x:', x.shape)
print ('xx:', xx.shape)
print (xx * x) 

x: (4,)
xx: (4, 1)
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]


In [20]:
y = np.ones(5)
print ("y shape : " , y.shape)
print ("x shape : " , x.shape)
print ("y : " , y)
print ("x : " , x )


y shape :  (5,)
x shape :  (4,)
y :  [ 1.  1.  1.  1.  1.]
x :  [0 1 2 3]


In [21]:
x + y # Generara un error pues las dimensiones no corresponden.

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [22]:
print (xx)
print (y)
xx + y 

[[0]
 [1]
 [2]
 [3]]
[ 1.  1.  1.  1.  1.]


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])

#### Metodos ya incluidos en la clase ndarray
Muchos metodos ya se encuentran integrados en la clase *ndarray* de NumPy

In [23]:
a = np.random.random((2,3))
a

array([[ 0.00499082,  0.24133393,  0.35971147],
       [ 0.73227603,  0.40573   ,  0.58216484]])

In [24]:
a.sum()

2.3262070921611939

In [25]:
a.min()

0.0049908217776630792

In [26]:
a.max()

0.73227603027262622

Por default estas operaciones se hacen sobre todos los elementos del arreglo, salvo que se especifiquen, que solo se desea hacer la operacion sobre algun eje en especifico.

In [27]:
# La suma de cada columna
a.sum(axis=0)

array([ 0.73726685,  0.64706393,  0.94187631])

In [28]:
# La suma de cada renglon
a.sum(axis=1)

array([ 0.60603622,  1.72017088])

In [29]:
# La suma aculumativa sobre cada renglon
b = np.arange(12).reshape(3,4)
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

### Funciones universales
Funciones matematicas que se realizan de elemento a elemento

Listado: http://docs.scipy.org/doc/numpy/reference/ufuncs.html#math-operations


In [30]:
np.sqrt(b)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
       [ 2.82842712,  3.        ,  3.16227766,  3.31662479]])

In [31]:
np.sin(b)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [32]:
c = np.array([2,2,2,2])
np.add(b,c)

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

### Seleccion de rangos, indexado e iteraciones
- Arreglos 1D se pueden acceder por indices, recortar e iterar sobre sus elementos, como una lista de python.
- Arreglos 2D, tienen un indice por eje, y estos indices se dan por un tipo de dato **tuple** 
- Arreglos multidimensionales tienen un indice por cada eje, de igual forma estan dados por un **tuple**

In [35]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

```matlab
% En matlab
>>> a = (0:9) .^ 2
```

In [47]:
print (a[2])
print (a[2:5])
print (a[0:-1:2])
print (a[np.array([2,4,6])])  # Elementos con indice 2 , 4 y 6

4
[ 4  9 16]
[ 0  4 16 36 64]
[ 4 16 36]


```matlab
% En matlab
>>> a(3)
>>> a(3:5)
>>> a(1:2:end)
>>> a([3,5,7])
```

In [48]:
# Usando los mismos arreglos para referirnos a indices de otro arreglo.
indices = np.array([5,8,1])
a[indices]

array([25, 64,  1])

In [49]:
# Modificando datos sobre una region del arreglo.
a[4:6] = -999
a

array([   0,    1,    4,    9, -999, -999,   36,   49,   64,   81])

In [50]:
# Iterar sobre sus elementos.
for el in a:
    print (el, ',')

0 ,
1 ,
4 ,
9 ,
-999 ,
-999 ,
36 ,
49 ,
64 ,
81 ,


```matlab
% En matlab
>>> for idx = 1:numel(a)
      a(idx)
    end  
```

In [51]:
# Arreglos multidimensionales

# Equivalente a 
# def func(x,y):
#   return 10 * x+y 
func = lambda x,y : 10*x+y 

b = np.fromfunction(func,(5,4))
b

array([[  0.,   1.,   2.,   3.],
       [ 10.,  11.,  12.,  13.],
       [ 20.,  21.,  22.,  23.],
       [ 30.,  31.,  32.,  33.],
       [ 40.,  41.,  42.,  43.]])

In [52]:
# Segundo renglon
b[1,:]

array([ 10.,  11.,  12.,  13.])

```matlab
% En matlab
>>> b(2,:)
```

In [53]:
# Ultima columna
b[:,-1]

array([  3.,  13.,  23.,  33.,  43.])

```matlab
% En matlab
>>> b(:,end)
```

In [54]:
# Iterando sobre arreglos multidimensionales.
for renglon in b:
    print (renglon , ',')

[ 0.  1.  2.  3.] ,
[ 10.  11.  12.  13.] ,
[ 20.  21.  22.  23.] ,
[ 30.  31.  32.  33.] ,
[ 40.  41.  42.  43.] ,


In [55]:
# El atributo flat entrega el iterable de todos los elementos del arreglo
for el in b.flat:
    print (el, ',', end="")

0.0 ,1.0 ,2.0 ,3.0 ,10.0 ,11.0 ,12.0 ,13.0 ,20.0 ,21.0 ,22.0 ,23.0 ,30.0 ,31.0 ,32.0 ,33.0 ,40.0 ,41.0 ,42.0 ,43.0 ,

### Ordenando, buscando y contando el arreglo.
Metodos para la busqueda y ordenado de datos en arreglos de numpy<br>
http://docs.scipy.org/doc/numpy/reference/routines.sort.html

In [56]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
# Elementos del arreglo, con alguna condicion
a[(a>2) & (a<9)]

array([3, 4, 5, 6, 7, 8])

In [58]:
# Indices de elementos que cumplan la siguiente condicion
np.argwhere((a>2) & (a<9))

array([[1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

In [59]:
# Indices
print (np.argmin(a))
print (np.argmax(a))

0
11


### Manipulando la forma de un arreglo

In [60]:
a = np.floor( np.random.random((3,4)) * 10 )
a

array([[ 3.,  4.,  6.,  7.],
       [ 1.,  3.,  8.,  0.],
       [ 2.,  8.,  2.,  2.]])

In [61]:
a.shape

(3, 4)

In [62]:
# Aplanamos el arreglo, (Regresa referencias al arreglo original!)
a.ravel()

array([ 3.,  4.,  6.,  7.,  1.,  3.,  8.,  0.,  2.,  8.,  2.,  2.])

```matlab
% En matlab
>>> a(:)
```

In [63]:
# arreglo a transpuesto
a.transpose() # O tambien a.T

array([[ 3.,  1.,  2.],
       [ 4.,  3.,  8.],
       [ 6.,  8.,  2.],
       [ 7.,  0.,  2.]])

```matlab
% En matlab
>>> a.'
```

In [64]:
# Modificamos la forma del arreglo con resize
a.resize(6,2)
a

array([[ 3.,  4.],
       [ 6.,  7.],
       [ 1.,  3.],
       [ 8.,  0.],
       [ 2.,  8.],
       [ 2.,  2.]])

In [65]:
# reshape entrega un nuevo arreglo
# Al incluir -1 en los parametros, dejamos que numpy calcule el tamaño adecuado
a.reshape(-1,6)

array([[ 3.,  4.,  6.,  7.,  1.,  3.],
       [ 8.,  0.,  2.,  8.,  2.,  2.]])

### Concatenando arreglos

In [66]:
a = np.floor( 10 * np.random.random((2,2)) )
b = np.floor( 10 * np.random.random((2,2)) )

In [67]:
# Apilando los arreglos verticalemente
np.vstack( (a,b) )

array([[ 5.,  3.],
       [ 8.,  3.],
       [ 0.,  8.],
       [ 4.,  9.]])

In [68]:
# Apilando horizontalmente
np.hstack((a,b))

array([[ 5.,  3.,  0.,  8.],
       [ 8.,  3.,  4.,  9.]])

```matlab
% En matlab
>>> [a b]
```

In [69]:
# Un arreglo de 1D 
c = np.array([1,2,3,4,5,6])
c

array([1, 2, 3, 4, 5, 6])

In [70]:
# Al agregar np.newaxis, creamos un arreglo 2D con los datos ordenados en la columna
d = c[:,np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

```matlab
% En matlab
>>> [1:6]
```

In [71]:
np.vstack((d,d))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [72]:
np.hstack((d,d,d))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

### Copia de datos y vistas
Operando arreglos multidimensionales, en ocasiones los datos se copian a un nuevo arreglo y en otras no, para evitar confusiones veremos los casos.

In [73]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
# El operados = no hace copia de los datos, solo pasa la referencia al 
# puntero donde esta la informacion
b = a 
b is a 

True

In [75]:
# Los cambios realizados en b, tambien afectan al arreglo a, esto sucede igual
# al pasar parametros en una funcion
b.resize(3,4)
a.shape

(3, 4)

#### Vistas o copia ligera
La diferencia con las vistas, es que dos objetos ndarray que observan a los mismos datos. <br>
Al hacer un recorte de un arreglo, estamos creado una vista.

In [76]:
c = a.view()
c is a 

False

In [77]:
# Cambiamos la forma de los datos en c, sin que se afecte en a
c.resize((12))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [78]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
# Pero al cambiar un dato en el arreglo a ...
a[0] = -9999
c

array([-9999, -9999, -9999, -9999,     4,     5,     6,     7,     8,
           9,    10,    11])

#### Copia real de datos
El metodo copy() hace una copia completa del arreglo y de sus datos.

In [80]:
d = a.copy()
d is a

False

In [81]:
d[0,0] = 5555
a

array([[-9999, -9999, -9999, -9999],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

In [82]:
d

array([[ 5555, -9999, -9999, -9999],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

### Arreglos con mascara
Para manejar arreglos de datos que puedan contener datos invalidos, por lo que es conveniente usar un arreglo con mascara para no incluir esos datos en las operaciones.<br>
Documentacion completa: http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

In [83]:
# Importar el modulo para arreglos con mascara
import numpy.ma as ma

In [84]:
x = np.array([1,2,-1,4,5,6,-1,8,9])
mx = ma.masked_array(x , mask=[0,0,1,0,0,0,1,0,0])
mx

masked_array(data = [1 2 -- 4 5 6 -- 8 9],
             mask = [False False  True False False False  True False False],
       fill_value = 999999)

In [85]:
# En todas las operaciones sobre el arreglo no se contaran los datos enmascarados.
mx.mean()

5.0

In [86]:
# Es posible crear una mascara con alguna condicion sobre el arreglo.
nmx = ma.masked_array(x , mask=(x <0))
nmx

masked_array(data = [1 2 -- 4 5 6 -- 8 9],
             mask = [False False  True False False False  True False False],
       fill_value = 999999)

In [87]:
# Accediendo a la mascara
mx.mask

array([False, False,  True, False, False, False,  True, False, False], dtype=bool)

In [88]:
# Recuperar los datos validos
mx.compressed()

array([1, 2, 4, 5, 6, 8, 9])

### Salvando sesion de trabajo y compartir con matlab
Metodos adicionales, para salvar, archivos de text, binarios comprimidos, etc: http://docs.scipy.org/doc/numpy/reference/routines.io.html

In [89]:
# Arreglos de trabajo
a = np.random.random((5,5))
b = np.floor(np.random.random((11,11)) * 10)

In [90]:
# Salvar mis datos en el archivo misesion.npz
np.savez('misesion',a=a,b=b)

In [91]:
# Recuperar mi sesion
data = np.load('misesion.npz')
data.keys()

['a', 'b']

In [92]:
data['a']

array([[ 0.49813426,  0.20798163,  0.22900648,  0.64099794,  0.59901575],
       [ 0.01428176,  0.04993008,  0.45190223,  0.59166329,  0.22731577],
       [ 0.50502271,  0.85182309,  0.14019591,  0.70946569,  0.22263034],
       [ 0.57157873,  0.13895513,  0.52257508,  0.52528196,  0.73849395],
       [ 0.4259528 ,  0.47200735,  0.24040086,  0.29127694,  0.50264835]])

#### Recuperar datos de un archivo .mat


In [95]:
from scipy.io import loadmat

mat = loadmat('datos.mat')
mat

{'__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Wed Sep 30 22:28:07 2015',
 '__version__': '1.0',
 'a': array([[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]], dtype=uint8),
 'b': array([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=uint8)}

In [96]:
mat['a']

array([[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]], dtype=uint8)

##### Salvar en un .mat

In [98]:
from scipy.io import savemat

savemat('salida.mat',{'a':a, 'b':b})